name: uptime
description: A flutter plugin to get system uptime from native side.
version: 0.0.1
author: Jakob Hoyer <funkytransistor@gmail.com>
homepage: https://github.com/Crimsons/uptime

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jakobhoyer.uptime
        pluginClass: UptimePlugin
      tizen:
        pluginClass: UptimeTizenPlugin
        fileName: uptime_tizen_plugin.h